sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - xsltproc
otp_release:
  - "18.3"

# The checkout made by Travis is a "detached HEAD". We switch back
# to a tag or a branch. This pleases our git_rmq fetch method in
# rabbitmq-components.mk and the proper tag/branch is selected in
# dependencies too.
#
# FIXME: There is still one problem: for builds triggered by a pull
# request, $TRAVIS_BRANCH contains the target branch name, not the
# source branch name. Therefore, we can't rely on automatic checkout
# of corresponding branches in dependencies. For instance, if the pull
# request comes from a branch "rabbitmq-server-123", based on "stable",
# then this command will checkout "stable" and we won't try to checkout
# "rabbitmq-server-123" in dependencies.
#
# We also make sure the "master" branch exists, because
# rabbitmq-components.mk expects it. If it's missing, we just create a
# fake branch pointing to the same commit as $TRAVIS_BRANCH.
before_script:
  - git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
  - git rev-parse --verify -q master -- || git branch master

script: make tests

cache:
  apt: true
