sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - xsltproc
otp_release:
  - "R16B03-1"
  - "17.5"
  - "18.2"

# The checkout made by Travis is a "detached HEAD". We switch back
# to a tag or a branch. This pleases our git_rmq fetch method in
# rabbitmq-components.mk and the proper tag/branch is selected in
# dependencies too.
#
# FIXME: There is still one problem: for builds triggered by a pull
# request, $TRAVIS_BRANCH contains the target branch name, not the
# soruce branch name. Therefore, we can't rely on automatic checkout
# of corresponding branches in dependencies. For instance, if the pull
# request comes from a branch "rabbitmq-server-123", based on "stable",
# then this command will checkout "stable" and we won't try to checkout
# "rabbitmq-server-123" in dependencies.
before_script: git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"

script: make tests

cache:
  apt: true
